# Generated by Django 5.2.1 on 2025-07-14 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioSensor', '0002_alter_usuariosensor_sensor_and_more'),
        ('consumoDinamico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumodinamico',
            name='usuarioSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsuarioSensor.usuariosensor'),
        ),
    ]
