# Generated by Django 5.2.1 on 2025-07-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccionUsuario',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefonoUsuario',
            field=models.CharField(default='', max_length=20),
        ),
    ]
