# Generated by Django 5.2.1 on 2025-07-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_usuario_passwordusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.FileField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
