# Generated by Django 5.2.1 on 2025-07-14 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0002_sensor_latitud_sensor_longitud'),
        ('Usuario', '0003_alter_usuario_passwordusuario'),
        ('UsuarioSensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sensor.sensor'),
        ),
        migrations.AlterField(
            model_name='usuariosensor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuario.usuario'),
        ),
    ]
