# Generated by Django 5.2.1 on 2025-06-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoMensaje', '0001_initial'),
        ('UsuarioSensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fechaEnvio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipoMensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoMensaje.tipomensaje')),
                ('usuarioSensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsuarioSensor.usuariosensor')),
            ],
        ),
    ]
