# Generated by Django 5.2.1 on 2025-07-14 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0001_initial'),
        ('TipoMensaje', '0001_initial'),
        ('UsuarioSensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipoMensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TipoMensaje.tipomensaje'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuarioSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsuarioSensor.usuariosensor'),
        ),
    ]
