# Generated by Django 5.2.1 on 2025-06-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsuarioSensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoEstatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumoEstatico', models.FloatField()),
                ('fechaCorte', models.DateTimeField(auto_now_add=True)),
                ('usuarioSensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsuarioSensor.usuariosensor')),
            ],
        ),
    ]
