# Generated by Django 5.2.1 on 2025-07-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
    ]
