# Generated by Django 5.2.1 on 2025-06-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAlerta', models.CharField(max_length=100)),
                ('mensaje_default', models.TextField()),
            ],
        ),
    ]
