# Generated by Django 5.2.1 on 2025-06-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUsuario',
            fields=[
                ('logUsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fechaCambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
