# Generated by Django 5.2.1 on 2025-06-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsUsuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logusuario',
            name='logUsuarioId',
        ),
        migrations.AddField(
            model_name='logusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
