# Generated by Django 5.2.1 on 2025-07-14 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsUsuario', '0002_remove_logusuario_logusuarioid_logusuario_id'),
        ('Usuario', '0003_alter_usuario_passwordusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuario.usuario'),
        ),
    ]
