# Generated by Django 5.2.1 on 2025-07-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsUsuario', '0003_alter_logusuario_usuario'),
        ('Usuario', '0005_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario'),
        ),
    ]
